### ISSUE TITLE
Why not use Radzen Google Map?

### ISSUE THREAD

**Issue by Sen-Gupta** [MSIH/Blazor-Radzen-Google-Places-Autocomplete#1]
Perhaps using Radzen Google Map , this can be turned into an address picker?

**Comment by MSIH** [comment]
Please explain how to use the Radzen Google Map as a places autocomplete.
https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenGoogleMap.razor.cs
https://blazor.radzen.com/googlemap
